version: "3.8"

services:
  dvg:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./backend/.env.dev
  dvg-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dvg_user
      - POSTGRES_PASSWORD=dvg_pass
      - POSTGRES_DB=dvg_dev
volumes:
  postgres_data:
